name: fiduceo-fcdr-tools-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6*
  #
  # dependencies (in alphabetical order)
  #
  - coverage >= 4.4
  - dask >= 0.15.2
  - netcdf4 >=1.2
  - numexpr >=2.6.2
  - numpy >=1.11
  - xarray >=0.8.2
  #
  # for testing only
  #
  # - pytest >=3.1,<3.2
  # - pytest-cov >=2.5.1,<2.6